# Generated by Django 6.1.1 on 2026-09-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_student_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Admission_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
