# Generated by Django 6.1.1 on 2026-09-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_student_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='exam_term',
            field=models.CharField(choices=[('term1', 'Term1'), ('term2', 'Term2'), ('term3', 'Term3')], default='term1', max_length=10),
        ),
    ]
